topic_extractor:
  description: >
    Scrape the given URL and extract all the Topic discussed as one or two line summary 
    and if there any URL provided as a reference for the topic extract it.
    ####
    URL : {URL}
  expected_output: > 
    A list of all the topics and their reference URL. Reference URL is optional.
  agent: topic_scraper